# Generated by Django 3.1 on 2020-08-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('Date', models.DateField(null=True)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('High', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Adjclose', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Volume', models.IntegerField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=20)),
                ('Date', models.DateField(null=True)),
                ('Open', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('High', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Low', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Close', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Adjclose', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Volume', models.IntegerField(null=True)),
            ],
        ),
    ]
